#!/usr/bin/env python

import os
import sys

INSTALLATION_PATH = os.path.dirname(os.path.realpath(__file__))
sys.path.insert(1, os.path.join(INSTALLATION_PATH, 'lib'))

import cmd
import ConfigParser
import subprocess
import shutil
import datetime
import tempfile
import plistlib

class AWAInterpreter(cmd.Cmd):
    """Entry point for command line handling."""

    webapp_base_path = INSTALLATION_PATH
    webapp_install_path = os.path.join(webapp_base_path, "installed")
    webapp_httpd_config_path = os.path.join(webapp_base_path, "httpd.conf")
    webapp_plist_config_path = '/Library/Server/Web/Config/apache2/webapps'
    package_path=os.path.join(webapp_base_path, "packages")

    env = dict(os.environ, PYTHONPATH=':'.join(sys.path))

    def __init__(self, completekey='tab', stdin=None, stdout=None):
        cmd.Cmd.__init__(self, completekey, stdin, stdout)
        self.prompt = "autowebapp: "
        self.initialCheckup()

    def initialCheckup(self):
        if not os.path.isdir('/Library/Server/Web/Config/apache2/webapps'):
            print "Impossible to find OS X Server webapps installation folder"
            print "Please, be sure to install OS X Server app and complete the initial configuration"
            sys.exit(1)
        for path in [self.webapp_install_path, self.webapp_httpd_config_path]:
            if not os.path.isdir(path):
                try:
                    os.mkdir(path)
                except OSError:
                    print "Impossible to create installation directory "+path
                    print "Please be sure to run this tool as root or check file permissions"
            else:
                if not os.access(path, os.W_OK):
                    print "Impossible to write inside installation directory "+path
                    print "Please be sure to run this tool as root or check file permissions"

    # <editor-fold desc="Tools">
    def packageExist(self, p):
        return os.path.isfile(os.path.join(self.package_path,p,"info.txt")) \
               and os.path.isfile(os.path.join(self.package_path,p,"package.info")) \
               and os.path.isfile(os.path.join(self.package_path,p,"run"))

    def installExist(self, p):
        return os.path.isfile(os.path.join(self.webapp_install_path, p, 'install.info'))

    def listPackages(self, filter=None):
        if not filter:
            validpackages = [ p for p in os.listdir(self.package_path) if self.packageExist(p) ]
        else:
            validpackages = [ p for p in os.listdir(self.package_path) if self.packageExist(p) and filter in p ]
        return validpackages

    def apacheVersionKey(self):
        output = subprocess.check_output(['apachectl', '-v'])
        for line in output.splitlines():
            if line.startswith('Server version'):
                line = line.replace('Server version: Apache/', '')
                parts = line.split('.')
                version = parts[0]+parts[1]
                return 'httpd'+version

    def splitOptions(self, line):
        parts = line.split()
        options = list()
        is_a_long_string=False
        long_string=""
        for part in parts:
            if is_a_long_string:
                if part.endswith('"') and not part.endswith('\\"'):
                    long_string = " ".join([long_string, part[:-1]])
                    long_string = long_string.replace('\\"', '"')
                    options.append(long_string)
                    is_a_long_string=False
                    long_string=""
                else:
                    long_string = " ".join([long_string, part])
            elif part.startswith('"'):
                is_a_long_string=True
                long_string=part[1:]
            else:
                options.append(part)
        return options





    # </editor-fold>

    # <editor-fold desc="CLI commands">
    def do_list(self, line):
        packages = self.listPackages(line)
        print '\n'.join(packages)

    def do_infos(self, line):
        with open(os.path.join(self.package_path,line,"info.txt")) as info:
            print info.read()

    def complete_infos(self, text, line, begidx, endidx):
        return self.listPackages(text)

    def do_details(self, line):
        self.do_infos(line)
        variables = ConfigParser.SafeConfigParser()
        variables.read(os.path.join(self.package_path,line,"variables.ini"))
        for section in variables.sections():
            for variable in variables.options(section):
                print "{} {}".format((section + "." + variable).ljust(40),variables.get(section, variable).ljust(40))

    def do_installed(self, line):
        dirty = list()
        print "Installation ID with related package"
        for installID in os.listdir(self.webapp_install_path):
            if self.installExist(installID):
                install_info_path=os.path.join(self.webapp_install_path, installID, 'install.info')
                install_info = ConfigParser.SafeConfigParser()
                install_info.read(install_info_path)
                print "{} {}".format(installID.ljust(40),install_info.get('installation','package').ljust(40))
            else:
                dirty.append(installID)
        if len(dirty) > 0:
            print ""
            print "We found invalid resources in the installation folder (existing folder but not a valid webapp)"
            print "We recommand you to check the content of those folder and remove it"
            for dirt in dirty:
                print os.path.join(self.webapp_install_path, dirt)

    def do_install(self, line):
        ids = self.splitOptions(line)
        count = len(ids)
        if count == 1:
            packageID=ids[0]
            installID=ids[0]
        elif count == 2:
            packageID=ids[0]
            installID=ids[1]
        else:
            print "You must specify one or two argument only. The first will be the webapp ID to install and the second (optional) the installation ID"
        
        if self.packageExist(packageID):
            if self.installExist(installID):
                print "Installation ID already used"
            elif os.path.isdir(os.path.join(self.webapp_install_path, installID,)):
                print "An artefact of installation already exist with this ID but don't seem complete"
                print """A wild "rm -rf """+os.path.join(self.webapp_install_path, installID,)+"""" is recommanded"""
            else:
                package_path=os.path.join(self.package_path, packageID)
                install_path=os.path.join(self.webapp_install_path, installID)

                os.mkdir(install_path)

                process = subprocess.Popen([os.path.join(package_path, "run"), '-p', install_path, '-c', 'install'], env=self.env)
                process.wait()

                if process.returncode == 0:
                    package_info_path=os.path.join(package_path, 'package.info')
                    install_info_path=os.path.join(install_path, 'install.info')

                    install_info = ConfigParser.SafeConfigParser()
                    install_info.read(package_info_path)

                    install_info.add_section('installation')
                    install_info.set('installation', 'installation_date', datetime.datetime.now().isoformat())
                    install_info.set('installation', 'package', packageID)

                    f = open(install_info_path, 'w')
                    install_info.write(f)
                    f.close()

                    self.do_refreshApacheSettings(installID)

                else:
                    print "We got a problem during installation."
                    print "Installation path dirty "+install_path
                    print "Please, try to figure what's wrong, fix it then clean the installation folder and start again."
        else:
            print "Package ID "+line+" invalid"

    def do_remove(self, line):
        for installID in self.splitOptions(line):
            if self.installExist(installID):
                install_path=os.path.join(self.webapp_install_path, installID)

                install_info_path=os.path.join(install_path, 'install.info')
                install_info = ConfigParser.SafeConfigParser()
                install_info.read(install_info_path)

                package_path=os.path.join(self.package_path, install_info.get('installation','package'))

                process = subprocess.Popen([os.path.join(package_path, "run"), '-p', install_path, '-c', 'remove'], env=self.env)
                process.wait()

                httpd_file_path = os.path.join(self.webapp_httpd_config_path, installID+'.conf')
                os.remove(httpd_file_path)
                webapp_file_path = os.path.join(self.webapp_plist_config_path, installID+'.plist')
                os.remove(webapp_file_path)

                shutil.rmtree(install_path)

                print "Package removed, if you haven't disabled the package from Server.app before this operation"
                print "We recommand you to reload apache with the following command:"
                print "apachectl restart"
            else:
                print "Package not installed"

    def do_refreshApacheSettings(self, line):
        for installID in self.splitOptions(line):
            if self.installExist(installID):
                install_path=os.path.join(self.webapp_install_path, installID)

                install_info_path=os.path.join(install_path, 'install.info')
                install_info = ConfigParser.SafeConfigParser()
                install_info.read(install_info_path)

                package_path=os.path.join(self.package_path, install_info.get('installation','package'))

                with tempfile.NamedTemporaryFile() as temp_file:
                    process = subprocess.Popen([os.path.join(package_path, "run"), '-p', install_path, '-c', self.apacheVersionKey(), '-f', temp_file.name], env=self.env)
                    process.wait()
                    temp_file.flush()
                    httpd_content = temp_file.read()

                with tempfile.NamedTemporaryFile() as temp_file:
                    process = subprocess.Popen([os.path.join(package_path, "run"), '-p', install_path, '-c', 'webapp', '-f', temp_file.name], env=self.env)
                    process.wait()
                    webapp_content = plistlib.readPlist(temp_file)

                httpd_file_path = os.path.join(self.webapp_httpd_config_path, installID+'.conf')
                with open(httpd_file_path, 'w') as httpd_file:
                    httpd_file.write(httpd_content)

                webapp_content['installationIndicatorFilePath'] = install_info_path

                if not 'includeFiles' in webapp_content:
                    webapp_content['includeFiles'] = list()
                webapp_content['includeFiles'].append(httpd_file_path)

                webapp_content['name'] = installID
                webapp_content['displayName'] = webapp_content['displayName']+" ("+installID+")"

                target_folder=""
                use_tmp_folder = False
                if os.access(self.webapp_plist_config_path, os.W_OK):
                    target_folder = self.webapp_plist_config_path
                else:
                    target_folder = "/tmp"
                    use_tmp_folder = True

                webapp_file_path = os.path.join(target_folder, installID+'.plist')
                plistlib.writePlist(webapp_content, webapp_file_path)

                print "WARNING: This tool isn't run as root, so we aren't able to properly deploy webapp settings for OS X Server"
                print "Please, run the following command as root to finish the installation."
                print ""
                print "mv "+webapp_file_path+" "+self.webapp_plist_config_path
                print ""
            else:
                print "Package not installed"

    def do_getSettings(self, line):
        parts = self.splitOptions(line)

        if len(parts) >= 1:
            installID = parts[0]
            if self.installExist(installID):
                install_path=os.path.join(self.webapp_install_path, installID)

                install_info_path=os.path.join(install_path, 'install.info')
                install_info = ConfigParser.SafeConfigParser()
                install_info.read(install_info_path)

                package_path=os.path.join(self.package_path, install_info.get('installation','package'))

                if len(parts) == 1:
                    process = subprocess.Popen([os.path.join(package_path, "run"), '-p', install_path, '-c', 'get'], env=self.env)
                    process.wait()
                else:
                    key = parts[1]
                    process = subprocess.Popen([os.path.join(package_path, "run"), '-p', install_path, '-c', 'get', '-k', key], env=self.env)
                    process.wait()
            else:
                print "Invalid specified installation ID"
        else:
            print "You must specify at least an installation ID"


    def do_setSettings(self, line):
        parts = self.splitOptions(line)
        if len(parts) == 3:
            installID = parts[0]
            key = parts[1]
            value= parts[2]
            if self.installExist(installID):
                install_path=os.path.join(self.webapp_install_path, installID)

                install_info_path=os.path.join(install_path, 'install.info')
                install_info = ConfigParser.SafeConfigParser()
                install_info.read(install_info_path)

                package_path=os.path.join(self.package_path, install_info.get('installation','package'))

                process = subprocess.Popen([os.path.join(package_path, "run"), '-p', install_path, '-c', 'set', '-k', key, '-s', value], env=self.env)
                process.wait()
            else:
                print "Invalid specified installation ID"
        else:
            print "You must specify installation ID, key and value"


    def do_unsetSettings(self, line):
        parts = self.splitOptions(line)
        if len(parts) == 2:
            installID = parts[0]
            key = parts[1]
            if self.installExist(installID):
                install_path=os.path.join(self.webapp_install_path, installID)

                install_info_path=os.path.join(install_path, 'install.info')
                install_info = ConfigParser.SafeConfigParser()
                install_info.read(install_info_path)

                package_path=os.path.join(self.package_path, install_info.get('installation','package'))

                process = subprocess.Popen([os.path.join(package_path, "run"), '-p', install_path, '-c', 'unset', '-k', key], env=self.env)
                process.wait()
            else:
                print "Invalid specified installation ID"
        else:
            print "You must specify installation ID, key and value"


    def do_EOF(self, line):
        return True

    def do_quit(self, line):
        return self.do_EOF(line)

    def do_exit(self, line):
        return self.do_EOF(line)
    # </editor-fold>

    # <editor-fold desc="CLI help">
    def help_list(self):
        print '\n'.join([
            "list <keyword>",
            "Show the list of availabe webapps for installation. If you specify a keyword, it will look for all webapp identifier containing it."
        ])

    def help_infos(self):
        print '\n'.join([
            "info [webapp]",
            "Display general infos for specified webapp."
        ])

    def help_details(self):
        print '\n'.join([
            "details [webapp]",
            "Display general infos for specified webapp plus available settings."
        ])

    def help_installed(self):
        print '\n'.join([
            "installed",
            "Show installed webapps."
        ])

    def help_install(self):
        print '\n'.join([
            "install webapp <installation ID>",
            "Install specified webapp.",
            "Additionnal argument can be used to specify installation ID. Usefull when one webapp is installed multiple time.",
            "Default installation ID is the webapp ID."
        ])

    def help_remove(self):
        print '\n'.join([
            "remove [installationID ...]",
            "Remove specified webapps, be careful, all related data will be lost.",
            "Installation ID is by default the webapp ID, but can be overrided to allow multiple instances"
        ])

    def help_refreshApacheSettings(self):
        print '\n'.join([
            "refreshApacheSettings [installationID ...]",
            "Regenerate webapp plist and apache configuration file for specified installation ID."
        ])

    def help_getSettings(self):
        print '\n'.join([
            "getSettings [webapp] <key>",
            "List webapp settings and value (only for installed one)."
        ])

    def help_setSettings(self):
        print '\n'.join([
            "setSettings [webapp] [key] [value]",
            "Set settings for installed webapp."
        ])

    def help_unsetSettings(self):
        print '\n'.join([
            "unsetSettings [webapp] [key]",
            "Remove settings for installed webapp."
        ])

    def help_EOF(self):
        print '\n'.join([
            "^D",
            "Press ctrl+D to properly exit from autowebapp shell."
        ])
# </editor-fold>


if __name__ == '__main__':
    if len(sys.argv) > 1:
        AWAInterpreter().onecmd(' '.join(sys.argv[1:]))
    else:
        AWAInterpreter().cmdloop()
