#!/usr/bin/env python

import os
import argparse
import subprocess
import ConfigParser
import shutil

TARGETPATH=""
KEY=""
VALUE=""
WORKPATH=os.path.dirname(os.path.realpath(__file__))

def do_remove():
    for root, dirs, files in os.walk(TARGETPATH, topdown=False):
        for name in files:
            path = os.path.join(root, name)
            if os.path.islink(path):
                os.unlink(path)
            else:
                os.remove(path)
        for name in dirs:
            path = os.path.join(root, name)
            if os.path.islink(path):
                os.unlink(path)
            else:
                os.rmdir(path)

def do_install():
    src_path = os.path.join(WORKPATH,'scripts')
    folder_content = os.listdir(src_path)
    folder_content.sort()
    for script in folder_content:
        script_path = os.path.join(src_path, script)
        if os.path.isfile(script_path):
            filename, file_extension = os.path.splitext(script_path)
            if file_extension == ".sh":
                process_args = [script_path, TARGETPATH]
                subprocess.call(process_args)


def do_set():
    config_path=TARGETPATH+"/munkiwebadmin/settings.ini"
    settings = ConfigParser.SafeConfigParser()
    settings.read(config_path)

    if KEY and VALUE:
        parts = KEY.split('.')
        partsCount = len(parts)
        if partsCount == 2:
            if not settings.has_section(parts[0]):
                settings.add_section(parts[0])
            settings.set(parts[0], parts[1], VALUE)
            print settings.get(parts[0], parts[1])
            f = open(config_path, 'w')
            settings.write(f)
            f.close()
        else:
            print "Invalid key format"
    else:
        print "You must specify a key (-k) and a value (-s) to set"

def do_get():
    config_path=TARGETPATH+"/munkiwebadmin/settings.ini"
    settings = ConfigParser.SafeConfigParser()
    settings.read(config_path)
    
    if KEY:
        parts = KEY.split('.')
        partsCount = len(parts)
        if partsCount == 1:
            for variable in settings.options(parts[0]):
                print "{} {}".format((parts[0] + "." + variable).ljust(40),settings.get(parts[0], variable).ljust(40))
        elif partsCount == 2:
            print settings.get(parts[0], parts[1])
        else:
            print "Invalid key format"
    else:
        for section in settings.sections():
            for variable in settings.options(section):
                print "{} {}".format((section + "." + variable).ljust(40),settings.get(section, variable).ljust(40))


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Install the package.')
    parser.add_argument('-p','--path', help='Deployment path', required=True)
    parser.add_argument('-c','--command', help='Command (install, remove, set, get)', required=True)
    parser.add_argument('-k','--key', help='The key to work with (commands: get, set)', required=False)
    parser.add_argument('-s','--set', help='The value to set (command: set)', required=False)

    args = vars(parser.parse_args())

    TARGETPATH = args['path']
    KEY = args['key']
    VALUE = args['set']
    
    if args['command'] == "install":
        do_install()
    elif args['command'] == "remove":
        do_remove()
    elif args['command'] == "get":
        do_get()
    elif args['command'] == "set":
        do_set()
    else:
        print "Supported commands are install, remove, get and set. Nothing else."
